service: carta-monitor
useDotenv: true

plugins:
    - serverless-plugin-typescript

provider:
    name: aws
    runtime: nodejs14.x
    region: us-east-1
    lambdaHashingVersion: 20201221

functions:
    send:
        handler: src/functions/send.send
        description: Healthcheck to ensure we are receiving sends
        environment:
            STAGE: ${opt:stage, "local"}
        events:
            - schedule: rate(10 minutes)
    sendScheduling:
        handler: src/functions/sendScheduling.sendScheduling
        description: Healthcheck to ensure we can schedule sends
        environment:
            STAGE: ${opt:stage, "local"}
        events:
            - schedule: rate(10 minutes)
    sender:
        handler: src/functions/sender.sender
        description: Healthcheck to ensure carta-sender can be successfully invoked
        environment:
            STAGE: ${opt:stage, "local"}
        events:
            - schedule: rate(10 minutes)
    testAlert:
        handler: src/functions/testAlert.testAlert
        description: Healthcheck to ensure we can send alerts
        environment:
            STAGE: ${opt:stage, "local"}
        events:
            - schedule: rate(10 minutes)
    metricsProcessing:
        handler: src/functions/metricsProcessing.checkMetricsProcessing
        description: Healthcheck to ensure metrics process
        environment:
            STAGE: ${opt:stage, "local"}
        events:
            - schedule: rate(10 minutes)
    fileDownloadProcessing:
        handler: src/functions/fileDownloadProcessing.checkFileDownloadProcessing
        description: Healthcheck to ensure file downloads are processing
        environment:
            STAGE: ${opt:stage, "local"}
        events:
            - schedule: rate(10 minutes)
    dynamicListProcessing:
        handler: src/functions/dynamicListProcessing.checkDynamicListProcessing
        description: Healthcheck to ensure dynamic lists are processing
        environment:
            STAGE: ${opt:stage, "local"}
        events:
            - schedule: rate(10 minutes)
    campaignSendAlerts:
        handler: src/functions/campaignSendAlerts.campaignSendAlerts
        description: todo
        environment:
            STAGE: ${opt:stage, "local"}
        events:
            - schedule: rate(10 minutes)
