service: carta-monitor
useDotenv: true

plugins:
    - serverless-plugin-typescript

provider:
    name: aws
    runtime: nodejs16.x
    region: us-east-1

functions:
    sendScheduling:
        handler: src/functions/sendScheduling.sendScheduling
        description: Healthcheck to ensure we can schedule sends
        environment:
            STAGE: ${opt:stage, "local"}
        events:
            - schedule: rate(10 minutes)
    ses:
        handler: src/functions/ses.ses
        description: Healthcheck to ensure our SES Client works
        environment:
            STAGE: ${opt:stage, "local"}
        events:
            - schedule: rate(10 minutes)
