service: carta-monitor

plugins:
    - serverless-plugin-typescript
    - serverless-offline

provider:
    name: aws
    runtime: nodejs18.x
    region: us-east-1

functions:
    healthcheck:
        handler: src/functions/healthcheck.healthcheck
        description: Healthcheck to ensure the service is up
        events:
            - http:
                  path: healthcheck
                  method: get
