service: carta-monitor
useDotenv: true

plugins:
    - serverless-plugin-typescript

provider:
    name: aws
    runtime: nodejs14.x
    region: us-east-1

functions:
    sendScheduling:
        handler: src/functions/sendScheduling.sendScheduling
        description: Healthcheck to ensure we can schedule sends
        environment:
            STAGE: ${opt:stage, "local"}
        events:
            - schedule: rate(10 minutes)
    ses:
        handler: src/functions/ses.ses
        description: Healthcheck to ensure our SES Client works
        environment:
            STAGE: ${opt:stage, "local"}
        events:
            - schedule: rate(10 minutes)
    testAlert:
        handler: src/functions/testAlert.testAlert
        description: Healthcheck to ensure we can send alerts
        environment:
            STAGE: ${opt:stage, "local"}
        events:
            - schedule: rate(10 minutes)
    metricsProcessing:
        handler: src/functions/metricsProcessing.checkMetricsProcessing
        description: Healthcheck to ensure metrics process
        environment:
            STAGE: ${opt:stage, "local"}
        events:
            - schedule: rate(10 minutes)
    fileDownloadProcessing:
        handler: src/functions/fileDownloadProcessing.checkFileDownloadProcessing
        description: Healthcheck to ensure file downloads are processing
        environment:
            STAGE: ${opt:stage, "local"}
        events:
            - schedule: rate(10 minutes)
